### PR TITLE
Jar task to gradle and updated Dockerfile. This should fix #19

### LINKED ISSUE #19: Docker image is in debug mode
The docker image published has the `debug` tag. I tried to build it without it but it doesn't work since `sh` is not installer anymore. I need to tackle this in order to make the whole stuff running without shell scripts

### PR DESCRIPTION
**Pull request by M0Rf30**
See commit comments to know other magic messages popped out

### CODE REVIEW

**Comment by Polpetta** [comment]
Yep. If you check how I built the `sh` script, I have to add it in the `application` block.
https://github.com/Polpetta/jkk/blob/5e8e992957ec2de1e7bbfd6c53ff2ebc918f2a27/build.gradle#L31-L34

**Comment by M0Rf30** [comment]
Yes I know. But I'm lookin for an elegant way to embed this argument in the generated jar (the MANIFEST if possible).

**Comment by M0Rf30** [comment]
No way. I added the argument to dockerfile entrypoint. It's seems the cleanest way

**Review by Polpetta — APPROVED** [review]
Fair enough! I'll merge it :+1:

**Pull request merged**
